#!/usr/bin/env python3
"""Restore this project's dependencies from GitHub only.

Replaces `qpm restore`, which resolves everything through qpackages.com. This
reads scripts/dependencies.json -- a self-contained manifest of repositories,
refs and release asset URLs -- and populates extern/ with the same layout qpm
produces, then regenerates extern.cmake.

    python3 scripts/restore-deps.py             # restore into ./extern
    python3 scripts/restore-deps.py --clean     # wipe extern/ first
    python3 scripts/restore-deps.py --check     # verify manifest, download nothing

Headers come from https://github.com/<repo>/archive/<ref>.tar.gz and native
libraries from their GitHub release assets. Nothing else is contacted.
"""

import argparse
import io
import json
import pathlib
import shutil
import sys
import tarfile
import urllib.error
import urllib.request

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
MANIFEST = HERE / "dependencies.json"
USER_AGENT = "vivify-quest-restore"


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request) as response:
        return response.read()


def extract_headers(dep: dict, includes: pathlib.Path) -> None:
    """Download <repo> at <ref> and unpack it to includes/<id>/."""
    repo, ref, dep_id = dep["repo"], dep["ref"], dep["id"]
    url = f"https://github.com/{repo}/archive/{ref}.tar.gz"
    print(f"  headers  {dep_id:<26} {repo}@{ref}")
    blob = fetch(url)

    destination = includes / dep_id
    if destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True)

    with tarfile.open(fileobj=io.BytesIO(blob), mode="r:gz") as archive:
        members = archive.getmembers()
        # GitHub wraps the tree in a single <repo>-<ref> directory; strip it so
        # includes/<id>/shared/... matches what #include paths expect.
        root = members[0].name.split("/", 1)[0] + "/" if members else ""
        for member in members:
            if not member.name.startswith(root):
                continue
            relative = member.name[len(root):]
            if not relative:
                continue
            # Refuse anything that would escape the destination directory.
            target = (destination / relative).resolve()
            if not str(target).startswith(str(destination.resolve())):
                raise RuntimeError(f"{dep_id}: archive entry escapes destination: {member.name}")
            if member.isdir():
                target.mkdir(parents=True, exist_ok=True)
            elif member.isreg():
                target.parent.mkdir(parents=True, exist_ok=True)
                source = archive.extractfile(member)
                if source is not None:
                    target.write_bytes(source.read())


def download_library(dep: dict, libs: pathlib.Path) -> None:
    url = dep.get("soLink")
    if not url:
        return
    name = dep.get("overrideSoName") or url.rsplit("/", 1)[-1]
    print(f"  library  {dep['id']:<26} {name}")
    (libs / name).write_bytes(fetch(url))


def generate_extern_cmake(manifest: dict) -> str:
    lines = [
        "# Generated by scripts/restore-deps.py from scripts/dependencies.json.",
        "# Do not edit by hand; re-run the script instead.",
        "target_include_directories(${COMPILE_ID} PRIVATE ${EXTERN_DIR}/includes)",
        "",
    ]
    for dep in manifest["dependencies"]:
        options = dep.get("compileOptions") or {}
        dep_id = dep["id"]
        for path in options.get("includePaths", []):
            lines.append(f"target_include_directories(${{COMPILE_ID}} PRIVATE ${{EXTERN_DIR}}/includes/{dep_id}/{path})")
        for path in options.get("systemIncludes", []):
            lines.append(
                f"target_include_directories(${{COMPILE_ID}} SYSTEM PRIVATE ${{EXTERN_DIR}}/includes/{dep_id}/{path})")
        for flag in options.get("cppFlags", []):
            lines.append(f"target_compile_options(${{COMPILE_ID}} PRIVATE {flag})")
    lines += [
        "",
        "target_link_directories(${COMPILE_ID} PRIVATE ${EXTERN_DIR}/libs)",
        "RECURSE_FILES(so_list ${EXTERN_DIR}/libs/*.so)",
        "RECURSE_FILES(a_list ${EXTERN_DIR}/libs/*.a)",
        "",
        "target_link_libraries(${COMPILE_ID} PRIVATE",
        "\t${so_list}",
        "\t${a_list}",
        ")",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--clean", action="store_true", help="remove extern/ before restoring")
    parser.add_argument("--check", action="store_true", help="validate the manifest without downloading")
    args = parser.parse_args()

    manifest = json.loads(MANIFEST.read_text())
    dependencies = manifest["dependencies"]

    incomplete = [d["id"] for d in dependencies if not d.get("repo") or not d.get("ref")]
    if incomplete:
        print("error: these dependencies do not name a source repository/ref:", file=sys.stderr)
        for dep_id in incomplete:
            print(f"  - {dep_id}", file=sys.stderr)
        print("\nRun scripts/discover-deps.py once against an existing extern/ tree", file=sys.stderr)
        print("to fill them in, then commit scripts/dependencies.json.", file=sys.stderr)
        return 1

    if args.check:
        print(f"Manifest OK: {len(dependencies)} dependencies, all with a repo and ref.")
        print(f"Native libraries: {sum(1 for d in dependencies if d.get('soLink'))}")
        return 0

    extern = ROOT / manifest.get("externDir", "extern")
    if args.clean and extern.exists():
        shutil.rmtree(extern)
    includes = extern / "includes"
    libs = extern / "libs"
    includes.mkdir(parents=True, exist_ok=True)
    libs.mkdir(parents=True, exist_ok=True)

    failures = []
    for dep in dependencies:
        try:
            extract_headers(dep, includes)
            download_library(dep, libs)
        except (urllib.error.URLError, urllib.error.HTTPError, RuntimeError, tarfile.TarError, OSError) as error:
            failures.append(f"{dep['id']}: {error}")
            print(f"  FAILED   {dep['id']:<26} {error}", file=sys.stderr)

    if failures:
        print(f"\n{len(failures)} dependency/dependencies failed to restore.", file=sys.stderr)
        return 1

    (ROOT / "extern.cmake").write_text(generate_extern_cmake(manifest))
    print(f"\nRestored {len(dependencies)} dependencies into {extern} and regenerated extern.cmake.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
